/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    proposals: Proposal;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    proposals: ProposalsSelect<false> | ProposalsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Que se ve, para quien no la ve. Si la imagen es decorativa y no aporta nada, una cadena vacia no vale: mejor no subirla a una coleccion que el sitio pinta.
   */
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * La direccion de la pieza. No se traduce.
   */
  slug: string;
  client?: string | null;
  year?: number | null;
  discipline?: ('branding' | 'web' | 'motion' | 'marketing') | null;
  summary?: string | null;
  cover: number | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Aparece en el escaparate del menu y en el manifiesto.
   */
  featured?: boolean | null;
  /**
   * Menor primero. Empata por fecha de creacion.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposals".
 */
export interface Proposal {
  id: number;
  client: string;
  contactEmail?: string | null;
  status: 'borrador' | 'enviada' | 'aceptada' | 'rechazada' | 'vencida';
  currency: 'MXN' | 'USD';
  validUntil?: string | null;
  /**
   * Se genera solo. La URL privada de esta propuesta cuelga de el.
   */
  accessToken?: string | null;
  /**
   * Interno. NUNCA sale al cliente — el adaptador de cms/ no lo mapea.
   */
  notes?: string | null;
  /**
   * El servicio: "Digital Growth Strategy".
   */
  serviceTitle?: string | null;
  /**
   * Una linea por renglon.
   */
  tagline?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * El titular del diagnostico.
   */
  headline?: string | null;
  /**
   * Donde esta el cliente hoy y que proponen las rutas.
   */
  context?: string | null;
  /**
   * La auditoria del sitio actual, en orden de lo que cuesta. El numero sale del orden.
   */
  findings?:
    | {
        /**
         * Se acuna sola desde el titulo. La usa S9b para atar entregables.
         */
        key?: string | null;
        /**
         * La etiqueta corta: captacion, calificacion, seguimiento.
         */
        area: string;
        /**
         * La afirmacion: "la ficha no capta ningun lead".
         */
        title: string;
        /**
         * Lo que cuesta hoy, en dinero o en tiempo del equipo.
         */
        cost: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Tres del mercado y una del cliente. Toda cifra va con su fuente.
   */
  figures?:
    | {
        /**
         * El numero tal y como se lee: "247,680 USD", "80%", "0".
         */
        value: string;
        /**
         * Que es ese numero.
         */
        label: string;
        /**
         * De donde sale. Obligatorio a proposito.
         */
        source: string;
        id?: string | null;
      }[]
    | null;
  baseTitle?: string | null;
  deliverables?:
    | {
        name: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Una linea por punto. Es una textarea y no una lista de filas: cada punto es UN dato, y seis filas plegables para seis frases es mas trabajo sin mas estructura.
   */
  includedInAll?: string | null;
  /**
   * El rotulo comun de las rutas.
   */
  routesEyebrow?: string | null;
  /**
   * Se declaran UNA vez. Cada ruta recibe su hueco automaticamente al guardar.
   */
  criteria?:
    | {
        label: string;
        /**
         * Se deriva de la etiqueta.
         */
        key?: string | null;
        id?: string | null;
      }[]
    | null;
  packages?:
    | {
        name: string;
        /**
         * Se deriva del nombre. Es lo que ata la ruta recomendada y las columnas de la comparativa, y NO se traduce.
         */
        key?: string | null;
        /**
         * El tinte que identifica la ruta. Numerado, no por color.
         */
        accent: 'uno' | 'dos' | 'tres';
        priceKind: 'fijo' | 'mensual' | 'rango';
        /**
         * En CENTAVOS enteros. 4800000 son $48,000.00
         */
        amountCents: number;
        /**
         * Extremo alto del rango, en CENTAVOS.
         */
        amountMaxCents?: number | null;
        unit: 'proyecto' | 'mes' | 'pieza';
        deliveryWeeks?: number | null;
        /**
         * Un parrafo por bloque, separados por linea en blanco.
         */
        body?: string | null;
        /**
         * Se rellena solo a partir de los criterios. Solo hay que escribir el valor.
         */
        values?:
          | {
              key?: string | null;
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  addOnsTitle?: string | null;
  addOnsIntro?: string | null;
  addOns?:
    | {
        name: string;
        priceKind: 'fijo' | 'mensual' | 'rango';
        /**
         * En CENTAVOS enteros. 4800000 son $48,000.00
         */
        amountCents: number;
        /**
         * Extremo alto del rango, en CENTAVOS.
         */
        amountMaxCents?: number | null;
        unit: 'proyecto' | 'mes' | 'pieza';
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * El nombre de la ruta recomendada. Al guardar se convierte en su clave, que es lo que casa en los dos idiomas.
   */
  recommendedPackage?: string | null;
  recHeadline?: string | null;
  recBody?: string | null;
  technicalNote?: string | null;
  termsTitle?: string | null;
  terms?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  closing?: string | null;
  scopeItems?:
    | {
        concept: string;
        detail?: string | null;
        /**
         * En CENTAVOS. 1500 son $15.00
         */
        amountCents: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'proposals';
        value: number | Proposal;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  year?: T;
  discipline?: T;
  summary?: T;
  cover?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposals_select".
 */
export interface ProposalsSelect<T extends boolean = true> {
  client?: T;
  contactEmail?: T;
  status?: T;
  currency?: T;
  validUntil?: T;
  accessToken?: T;
  notes?: T;
  serviceTitle?: T;
  tagline?: T;
  coverImage?: T;
  headline?: T;
  context?: T;
  findings?:
    | T
    | {
        key?: T;
        area?: T;
        title?: T;
        cost?: T;
        id?: T;
      };
  figures?:
    | T
    | {
        value?: T;
        label?: T;
        source?: T;
        id?: T;
      };
  baseTitle?: T;
  deliverables?:
    | T
    | {
        name?: T;
        description?: T;
        id?: T;
      };
  includedInAll?: T;
  routesEyebrow?: T;
  criteria?:
    | T
    | {
        label?: T;
        key?: T;
        id?: T;
      };
  packages?:
    | T
    | {
        name?: T;
        key?: T;
        accent?: T;
        priceKind?: T;
        amountCents?: T;
        amountMaxCents?: T;
        unit?: T;
        deliveryWeeks?: T;
        body?: T;
        values?:
          | T
          | {
              key?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  addOnsTitle?: T;
  addOnsIntro?: T;
  addOns?:
    | T
    | {
        name?: T;
        priceKind?: T;
        amountCents?: T;
        amountMaxCents?: T;
        unit?: T;
        description?: T;
        id?: T;
      };
  recommendedPackage?: T;
  recHeadline?: T;
  recBody?: T;
  technicalNote?: T;
  termsTitle?: T;
  terms?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  closing?: T;
  scopeItems?:
    | T
    | {
        concept?: T;
        detail?: T;
        amountCents?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}